# -----------------------------------------------------------------------------
#  User configuration
# -----------------------------------------------------------------------------

title:               Von's Blog

# The unique resource location of your page.
# Set to `https://<username>.github.io` when hosting on GitHub Pages (and not using custom domains!)
url:                https://iamvon.github.io/

# Set to '' when hosting a blog on GitHub Pages, ie on `//<username>.github.io`
# Set to '/<reponame>' when using the `gh-pages` branch of a repository
baseurl:             /iamvon.github.io

# A very short description  of your page
tagline: Code runs my life

# A longer description of the page, used in the sidebar and as fallback for the meta description tag.
# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:         >
   *Code runs my life*



# This should be the same author as first in `_data/authors.yml`
author:
  name:              von
  email:             iamvon.blog@gmail.com

# Fallback image and color if not overwritten
#image:               
color:               '#0083a0'

# Remove to disable Google Fonts
google_fonts:        Roboto+Slab:700|Open+Sans:400,400i,700,700i
font_heading:        "'Roboto Slab', Helvetica, Arial, sans-serif"
font:                "'Open Sans', Georgia, Noto Serif, serif "

# Remove to disable Google Anaylics
google_analytics:    UA-100692169-1

# Setting a disqus shortname will enable the comment section on pages
# that have `comments: true` in the front matter
# disqus_shortname:
# This text will appear in the footer of every page. Markdown enabled.
copyright:           'Copyright &copy; 2017 Von'sBlog'

# Set to true when building locally with the `--lsi` option
# See: https://jekyllrb.com/docs/variables/#site-variables, `site.related_posts`
use_lsi:             false

# Set to `true` if you don't want to show an icon after each link that opens to an external site
no_mark_external:    true

# Format of the permalinks
permalink:           pretty

# Pagination configuration (used by the `blog` layout)
paginate:            5
paginate_path:       '/page-:num/'

# so that existing subscribers to your feed continue to receive updates.
# feed:
#   path:              atom.xml

# -----------------------------------------------------------------------------
#  Collections
# -----------------------------------------------------------------------------

collections:
  featured_categories:
    permalink:       /category/:name/
    output:          true
  featured_tags:
    permalink:       /tag/:name/
    output:          true
  projects:
    permalink:       /projects/:path/
    output:          true

# -----------------------------------------------------------------------------
#  Advanced configuration
# -----------------------------------------------------------------------------

gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-redirect-from
  - jemoji
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-github-comments
  
exclude:
  - README.md
  - LICENSE.md
  - node_modules
  - package.json
  - Gemfile
  - Gemfile.lock
  - jekyll-theme.gemspec
 
kramdown:
  footnote_backlink: '&#x21a9;&#xfe0e;'
  math_engine:       mathjax
  math_engine_opts:
    preview:         true
    preview_as_code: true

compress_html:
  comments:          ["<!-- ", " -->"]
  clippings:         all
  endings:           all
  ignore:
    envs:            [development]

sass:
  style:             compressed
